"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_env_path = BASE_DIR / ".env"
if _env_path.exists():
    try:
        for raw_line in _env_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip().strip("\"'")
            if k:
                os.environ[k] = v
    except Exception:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-##nwy=7uoi&ekzp+tvn3ykl9+tr(o9@gpydbd(#*(2n1%1gox+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.2.7',
    '127.0.0.1',
    '192.168.101.6',
    '192.168.2.17',
    '192.168.101.16',
    '192.168.101.7',
    '192.168.2.8',
    '192.168.1.171',
    '192.168.40.120',
    '192.168.0.100',
    '192.168.1.171',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'elecom_auth',
    'elecom_voting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '../frontend/org_elecom'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "elecom_db"),
        # Use a least-privileged role in production (see db/ledger_security.sql).
        "USER": os.getenv("DB_USER", "elecom_backend"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Local dev fallback: if env vars are not set, allow running against the
# existing local postgres credentials while DEBUG=True.
if DEBUG:
    if not DATABASES["default"].get("PASSWORD"):
        DATABASES["default"]["USER"] = os.getenv("DB_USER", "postgres")
        DATABASES["default"]["PASSWORD"] = os.getenv("DB_PASSWORD", "123")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/elecom_static'

STATICFILES_DIRS = [
    BASE_DIR.parent / 'frontend',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# This tells Django where to look for your CSS and Images
STATICFILES_DIRS = [
    BASE_DIR.parent / "frontend", 
]

CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME", "")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY", "")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET", "")

# Face++ (Megvii) — server only; never ship keys in the mobile app.
FACEPP_API_KEY = os.getenv("FACEPP_API_KEY", "")
FACEPP_API_SECRET = os.getenv("FACEPP_API_SECRET", "")
FACEPP_FACESET_OUTER_ID = os.getenv("FACEPP_FACESET_OUTER_ID", "elecom_voters")
FACEPP_API_BASE = os.getenv(
    "FACEPP_API_BASE",
    "https://api-us.faceplusplus.com/facepp/v3",
)
try:
    FACEPP_DUPLICATE_THRESHOLD = float(os.getenv("FACEPP_DUPLICATE_THRESHOLD", "80"))
except ValueError:
    FACEPP_DUPLICATE_THRESHOLD = 80.0
try:
    FACEPP_VERIFY_THRESHOLD = float(os.getenv("FACEPP_VERIFY_THRESHOLD", "80"))
except ValueError:
    FACEPP_VERIFY_THRESHOLD = 80.0

# Minutes a successful face verify remains valid before vote submit (server-enforced).
FACE_VOTE_VERIFY_SESSION_MINUTES = int(os.getenv("FACE_VOTE_VERIFY_SESSION_MINUTES", "20"))

# -- Email (Forgot Password OTP) -----------------------------------------------
# Default is console: OTPs are printed to the runserver terminal only — no real
# inbox delivery. For Gmail (or any SMTP), set in .env on the machine that runs Django:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=true
#   EMAIL_HOST_USER=your.address@gmail.com
#   EMAIL_HOST_PASSWORD=<app password if 2FA, or account password>
#   DEFAULT_FROM_EMAIL=ELECOM <your.address@gmail.com>
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST        = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT        = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS     = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_HOST_USER   = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
# Gmail copies app passwords as four groups with spaces; SMTP auth needs one string.
if EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD.replace(" ", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "ELECOM <noreply@elecom.app>")

# OTP validity window in minutes.
OTP_EXPIRY_MINUTES = int(os.getenv("OTP_EXPIRY_MINUTES", "10"))
# Reset token validity window in minutes (after OTP verified).
RESET_TOKEN_EXPIRY_MINUTES = int(os.getenv("RESET_TOKEN_EXPIRY_MINUTES", "15"))
