from django.contrib import admin
from django.urls import path
from django.shortcuts import redirect
from .views import (
    admin_candidates_bulk_delete_api,
    admin_candidates_create_api,
    admin_candidates_delete_api,
    admin_candidates_detail_api,
    admin_candidates_list_api,
    admin_candidates_update_api,
    admin_voters_delete_api,
    admin_voters_import_api,
    admin_voters_list_api,
    admin_voters_update_api,
    admin_page_token_api,
    admin_secure_page_view,
    admin_verify_password_api,
    admin_backup_create_api,
    admin_backup_delete_api,
    admin_backup_download_api,
    admin_backup_history_api,
    admin_backup_restore_api,
    admin_backup_settings_api,
    edit_election_dates,
    elevote_chat_api,
    backup_restore_page,
    election_reports,
    election_results,
    account_profile_api,
    account_app_rating_api,
    account_profile_photo_api,
    account_profile_update_api,
    account_profile_password_api,
    candidates_metrics_api,
    candidate_application_parties_api,
    candidates_list_api,
    candidate_application_submit_api,
    candidate_application_status_api,
    admin_candidate_applications_list_api,
    admin_candidate_application_decision_api,
    candidates_search_api,
    election_window_api,
    eligible_ballot_api,
    vote_status_api,
    vote_receipt_api,
    vote_submit_api,
    vote_ledger_api,
    vote_ledger_verify_api,
    user_results_api,
    results_analytics_api,
    cloudinary_signature_api,
    face_enrollment_status_api,
    face_enrollment_upsert_api,
    face_verify_for_vote_api,
    face_verification_verify_api,
    forgot_password_send_otp_api,
    forgot_password_verify_otp_api,
    forgot_password_reset_password_api,
    admin_cloudinary_signature_api,
    admin_dashboard_api,
    admin_elections_api,
    admin_election_window_api,
    admin_election_finalize_hash_api,
    admin_app_rating_notifications_api,
    admin_results_api,
    admin_reports_summary_api,
    admin_reset_notifications_api,
    admin_reset_status_api,
    admin_reset_votes_api,
    admin_network_settings_api,
    admin_network_logs_api,
    check_network_access_api,
    user_notifications_list_api,
    user_notifications_create_api,
    user_notifications_mark_read_api,
    user_notifications_mark_all_read_api,
    user_notifications_mark_unread_api,
    user_notifications_pin_api,
    user_notifications_delete_api,
    mobile_tutorial_state_api,
    login_view,
    terms_conditions_view,
)

def home_redirect(request):
    return redirect('/login/')

urlpatterns = [
    path('', home_redirect),
    path('g/<path:token>/', admin_secure_page_view, name='admin_secure_page_view'),
    path("elections/<int:election_id>/edit-dates/", edit_election_dates, name="edit_election_dates"),
    path("elections/<int:election_id>/results/", election_results, name="election_results"),
    path("elections/<int:election_id>/reports/", election_reports, name="election_reports"),
    path("backup/", backup_restore_page, name="backup_restore_page"),
    path("backup/history/", admin_backup_history_api, name="admin_backup_history_api"),
    path("backup/settings/", admin_backup_settings_api, name="admin_backup_settings_api"),
    path("backup/create/", admin_backup_create_api, name="admin_backup_create_api"),
    path("backup/download/<int:backup_id>/", admin_backup_download_api, name="admin_backup_download_api"),
    path("backup/restore/", admin_backup_restore_api, name="admin_backup_restore_api"),
    path("backup/delete/<int:backup_id>/", admin_backup_delete_api, name="admin_backup_delete_api"),
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'), # Access at 127.0.0.1:8000/login/
    path('terms-and-conditions/', terms_conditions_view, name='terms_conditions'),
    path('api/admin/dashboard/', admin_dashboard_api, name='admin_dashboard_api'),
    path('api/election/window/', election_window_api, name='election_window_api'),
    path('api/ballot/', eligible_ballot_api, name='eligible_ballot_api'),
    path('api/vote/status/', vote_status_api, name='vote_status_api'),
    path('api/vote/receipt/', vote_receipt_api, name='vote_receipt_api'),
    path('api/vote/submit/', vote_submit_api, name='vote_submit_api'),
    path('api/vote/ledger/', vote_ledger_api, name='vote_ledger_api'),
    path('api/vote/ledger/verify/', vote_ledger_verify_api, name='vote_ledger_verify_api'),
    path('api/candidates/metrics/', candidates_metrics_api, name='candidates_metrics_api'),
    path('api/cloudinary/signature/', cloudinary_signature_api, name='cloudinary_signature_api'),
    path('api/account/profile/', account_profile_api, name='account_profile_api'),
    path('api/account/app-rating/', account_app_rating_api, name='account_app_rating_api'),
    path('api/account/profile/photo/', account_profile_photo_api, name='account_profile_photo_api'),
    path('api/account/profile/update/', account_profile_update_api, name='account_profile_update_api'),
    path('api/account/profile/password/', account_profile_password_api, name='account_profile_password_api'),
    path('api/admin/cloudinary/signature/', admin_cloudinary_signature_api, name='admin_cloudinary_signature_api'),
    path('api/admin/candidates/list/', admin_candidates_list_api, name='admin_candidates_list_api'),
    path('api/admin/candidates/detail/', admin_candidates_detail_api, name='admin_candidates_detail_api'),
    path('api/admin/candidates/create/', admin_candidates_create_api, name='admin_candidates_create_api'),
    path('api/admin/candidates/update/', admin_candidates_update_api, name='admin_candidates_update_api'),
    path('api/admin/candidates/delete/', admin_candidates_delete_api, name='admin_candidates_delete_api'),
    path('api/admin/candidates/bulk-delete/', admin_candidates_bulk_delete_api, name='admin_candidates_bulk_delete_api'),
    path('api/admin/candidate-applications/list/', admin_candidate_applications_list_api, name='admin_candidate_applications_list_api'),
    path('api/admin/candidate-applications/decision/', admin_candidate_application_decision_api, name='admin_candidate_application_decision_api'),
    path('api/admin/voters/list/', admin_voters_list_api, name='admin_voters_list_api'),
    path('api/admin/voters/import/', admin_voters_import_api, name='admin_voters_import_api'),
    path('api/admin/voters/delete/', admin_voters_delete_api, name='admin_voters_delete_api'),
    path('api/admin/voters/update/', admin_voters_update_api, name='admin_voters_update_api'),
    path('api/admin/page-token/', admin_page_token_api, name='admin_page_token_api'),
    path('api/admin/verify-password/', admin_verify_password_api, name='admin_verify_password_api'),
    path('api/admin/results/', admin_results_api, name='admin_results_api'),
    path('api/results/', user_results_api, name='user_results_api'),
    path('api/results/analytics/', results_analytics_api, name='results_analytics_api'),
    path('api/admin/elections/', admin_elections_api, name='admin_elections_api'),
    path('api/admin/election-window/', admin_election_window_api, name='admin_election_window_api'),
    path('api/admin/election/final-hash/', admin_election_finalize_hash_api, name='admin_election_finalize_hash_api'),
    path('api/admin/notifications/app-ratings/', admin_app_rating_notifications_api, name='admin_app_rating_notifications_api'),
    path('api/admin/reports/summary/', admin_reports_summary_api, name='admin_reports_summary_api'),
    path('api/admin/reset/status/', admin_reset_status_api, name='admin_reset_status_api'),
    path('api/admin/reset/votes/', admin_reset_votes_api, name='admin_reset_votes_api'),
    path('api/admin/reset/notifications/', admin_reset_notifications_api, name='admin_reset_notifications_api'),
    path('api/admin/network-settings/', admin_network_settings_api, name='admin_network_settings_api'),
    path('api/admin/network-logs/', admin_network_logs_api, name='admin_network_logs_api'),
    path('api/network/check/', check_network_access_api, name='check_network_access_api'),

    # Mobile namespace (same handlers; cleaner URL separation for Flutter clients)
    path('api/mobile/election/window/', election_window_api, name='mobile_election_window_api'),
    path('api/mobile/ballot/', eligible_ballot_api, name='mobile_eligible_ballot_api'),
    path('api/mobile/vote/status/', vote_status_api, name='mobile_vote_status_api'),
    path('api/mobile/vote/receipt/', vote_receipt_api, name='mobile_vote_receipt_api'),
    path('api/mobile/vote/submit/', vote_submit_api, name='mobile_vote_submit_api'),
    path('api/mobile/vote/ledger/', vote_ledger_api, name='mobile_vote_ledger_api'),
    path('api/mobile/vote/ledger/verify/', vote_ledger_verify_api, name='mobile_vote_ledger_verify_api'),
    path('api/mobile/results/', user_results_api, name='mobile_user_results_api'),
    path('api/mobile/results/analytics/', results_analytics_api, name='mobile_results_analytics_api'),
    path('api/mobile/candidates/metrics/', candidates_metrics_api, name='mobile_candidates_metrics_api'),
    path('api/mobile/candidates/search/', candidates_search_api, name='mobile_candidates_search_api'),
    path('api/mobile/candidates/', candidates_list_api, name='mobile_candidates_list_api'),
    path('api/mobile/candidate-applications/parties/', candidate_application_parties_api, name='mobile_candidate_application_parties_api'),
    path('api/mobile/candidate-applications/submit/', candidate_application_submit_api, name='mobile_candidate_application_submit_api'),
    path('api/mobile/candidate-applications/status/', candidate_application_status_api, name='mobile_candidate_application_status_api'),
    path('api/mobile/account/profile/', account_profile_api, name='mobile_account_profile_api'),
    path('api/mobile/account/app-rating/', account_app_rating_api, name='mobile_account_app_rating_api'),
    path('api/mobile/elevote/chat/', elevote_chat_api, name='mobile_elevote_chat_api'),
    path('api/mobile/account/profile/photo/', account_profile_photo_api, name='mobile_account_profile_photo_api'),
    path('api/mobile/account/profile/update/', account_profile_update_api, name='mobile_account_profile_update_api'),
    path('api/mobile/account/profile/password/', account_profile_password_api, name='mobile_account_profile_password_api'),
    path('api/mobile/face/enrollment/status/', face_enrollment_status_api, name='mobile_face_enrollment_status_api'),
    path('api/mobile/face/enrollment/save/', face_enrollment_upsert_api, name='mobile_face_enrollment_upsert_api'),
    path('api/mobile/face/verify/', face_verify_for_vote_api, name='mobile_face_verify_for_vote_api'),
    path('api/mobile/face/verification/verify/', face_verification_verify_api, name='mobile_face_verification_verify_api'),
    path('api/mobile/network/check/', check_network_access_api, name='mobile_check_network_access_api'),
    path('api/mobile/auth/forgot-password/', forgot_password_send_otp_api, name='mobile_forgot_password_send_otp_api'),
    path('api/mobile/auth/verify-otp/', forgot_password_verify_otp_api, name='mobile_forgot_password_verify_otp_api'),
    path('api/mobile/auth/reset-password/', forgot_password_reset_password_api, name='mobile_forgot_password_reset_password_api'),
    path('api/mobile/tutorial/state/', mobile_tutorial_state_api, name='mobile_tutorial_state_api'),
    path('api/mobile/notifications/', user_notifications_list_api, name='mobile_user_notifications_list_api'),
    path('api/mobile/notifications/create/', user_notifications_create_api, name='mobile_user_notifications_create_api'),
    path('api/mobile/notifications/read/', user_notifications_mark_read_api, name='mobile_user_notifications_mark_read_api'),
    path('api/mobile/notifications/read-all/', user_notifications_mark_all_read_api, name='mobile_user_notifications_mark_all_read_api'),
    path('api/mobile/notifications/unread/', user_notifications_mark_unread_api, name='mobile_user_notifications_mark_unread_api'),
    path('api/mobile/notifications/pin/', user_notifications_pin_api, name='mobile_user_notifications_pin_api'),
    path('api/mobile/notifications/delete/', user_notifications_delete_api, name='mobile_user_notifications_delete_api'),

    path('api/mobile/admin/dashboard/', admin_dashboard_api, name='mobile_admin_dashboard_api'),
    path('api/mobile/admin/elections/', admin_elections_api, name='mobile_admin_elections_api'),
    path('api/mobile/admin/results/', admin_results_api, name='mobile_admin_results_api'),
    path('api/mobile/admin/election-window/', admin_election_window_api, name='mobile_admin_election_window_api'),
    path('api/mobile/admin/reports/summary/', admin_reports_summary_api, name='mobile_admin_reports_summary_api'),
    path('api/mobile/admin/reset/status/', admin_reset_status_api, name='mobile_admin_reset_status_api'),
    path('api/mobile/admin/reset/votes/', admin_reset_votes_api, name='mobile_admin_reset_votes_api'),
    path('api/mobile/admin/reset/notifications/', admin_reset_notifications_api, name='mobile_admin_reset_notifications_api'),
    path('api/mobile/admin/network-settings/', admin_network_settings_api, name='mobile_admin_network_settings_api'),
    path('api/mobile/admin/network-logs/', admin_network_logs_api, name='mobile_admin_network_logs_api'),
    path('api/mobile/admin/cloudinary/signature/', admin_cloudinary_signature_api, name='mobile_admin_cloudinary_signature_api'),
    path('api/mobile/admin/candidates/list/', admin_candidates_list_api, name='mobile_admin_candidates_list_api'),
    path('api/mobile/admin/candidates/detail/', admin_candidates_detail_api, name='mobile_admin_candidates_detail_api'),
    path('api/mobile/admin/candidates/create/', admin_candidates_create_api, name='mobile_admin_candidates_create_api'),
    path('api/mobile/admin/candidates/update/', admin_candidates_update_api, name='mobile_admin_candidates_update_api'),
    path('api/mobile/admin/candidates/delete/', admin_candidates_delete_api, name='mobile_admin_candidates_delete_api'),
    path('api/mobile/admin/candidates/bulk-delete/', admin_candidates_bulk_delete_api, name='mobile_admin_candidates_bulk_delete_api'),
    path('api/mobile/admin/candidate-applications/list/', admin_candidate_applications_list_api, name='mobile_admin_candidate_applications_list_api'),
    path('api/mobile/admin/candidate-applications/decision/', admin_candidate_application_decision_api, name='mobile_admin_candidate_application_decision_api'),
    path('api/mobile/admin/voters/list/', admin_voters_list_api, name='mobile_admin_voters_list_api'),
    path('api/mobile/admin/voters/import/', admin_voters_import_api, name='mobile_admin_voters_import_api'),
    path('api/mobile/admin/voters/delete/', admin_voters_delete_api, name='mobile_admin_voters_delete_api'),
    path('api/mobile/admin/voters/update/', admin_voters_update_api, name='mobile_admin_voters_update_api'),
]
