# Generated by Django 4.2.29 on 2026-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElecomStudent',
            fields=[
                ('id_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElecomUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=64, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('role', models.CharField(max_length=32)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
