# Generated by Django 4.2.29 on 2026-04-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecom_voting', '0003_voteitem_unique_position_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64)),
                ('rating', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=32)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_ratings',
            },
        ),
        migrations.AddIndex(
            model_name='apprating',
            index=models.Index(fields=['student_id', 'created_at'], name='app_ratings_student_373ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='apprating',
            index=models.Index(fields=['rating'], name='app_ratings_rating_b76a4c_idx'),
        ),
    ]
